name: create_monthlyreview
on:
  schedule:
    - cron: "5 0 1 * *"
  workflow_dispatch:

jobs:
  create_monthlyreviewlist:
    name: Create Monthly Review List
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date + '%Y/%m/%d')"
      - name: Generate GitHub Apps token
        id: generate
        uses: actions/create-github-app-token@67e27a7eb7db372a1c61a7f9bdab8699e9ee57f7 # v1.11.3
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Create New Issue
        env:
          GITHUB_TOKEN: ${{ steps.generate.outputs.token }}
        run: |
          gh issue create \
          --title "Monthly Tasks - ${{ steps.date.outputs.date }}" \
          --body "$(cat ./.github/ISSUE_TEMPLATE/monthyreview.md  | tail -n +8)"
